export const GAMES = [
    {
        id: "spacehuggers",
        title: "Space Huggers",
        kind: "web",
        description: "Run-and-Gun mit zerstörbarer Umgebung. Pfeiltasten laufen/springen, Z schießt, X rollt, C wirft Granaten. Bis zu 4 Spieler mit Gamepads.",
        score: { label: "Kills", order: "desc", format: "number" },
        author: "Frank Force",
        license: "GPL-3.0",
        source: "https://github.com/KilledByAPixel/SpaceHuggers",
    },
    {
        id: "radiusraid",
        title: "Radius Raid",
        kind: "web",
        description: "Space-Shooter: WASD bewegt, Maus zielt und schießt, F für Dauerfeuer.",
        score: { label: "Punkte", order: "desc", format: "number" },
        author: "Jack Rugile",
        license: "MIT",
        source: "https://github.com/jackrugile/radius-raid-js13k",
    },
    {
        id: "hexgl",
        title: "HexGL",
        kind: "web",
        description: "Futuristisches Rennspiel. Pfeiltasten lenken, schnellste Zeit über 3 Runden gewinnt.",
        score: { label: "Zeit", order: "asc", format: "time" },
        author: "Thibaut Despoulain",
        license: "MIT",
        source: "https://github.com/BKcore/HexGL",
    },
    {
        id: "dabg",
        title: "Double Action Blaster Guys",
        kind: "retro",
        system: "NES",
        core: "nes",
        rom: "dabg.nes",
        players: "1–2 (Koop)",
        description: "Action-Plattformer mit 52 Leveln, zu zweit spielbar.",
        author: "NovaSquirrel",
        license: "zlib",
        source: "https://github.com/NovaSquirrel/DABG",
    },
    {
        id: "rhde",
        title: "RHDE: Furniture Fight",
        kind: "retro",
        system: "NES",
        core: "nes",
        rom: "rhde.nes",
        players: "2 (gegeneinander)",
        description: "Haus bauen, Haus verteidigen – Duell für zwei.",
        author: "Damian Yerrick",
        license: "GNU All-Permissive",
        source: "https://github.com/pinobatch/rhde-nes",
    },
    {
        id: "thwaite",
        title: "Thwaite",
        kind: "retro",
        system: "NES",
        core: "nes",
        rom: "thwaite.nes",
        players: "1–2",
        description: "Raketenabwehr im Stil von Missile Command.",
        author: "Damian Yerrick",
        license: "GPL-3.0",
        source: "https://github.com/pinobatch/thwaite-nes",
    },
    {
        id: "nova",
        title: "Nova the Squirrel",
        kind: "retro",
        system: "NES",
        core: "nes",
        rom: "nova.nes",
        players: "1",
        description: "Polierter Action-Plattformer.",
        author: "NovaSquirrel",
        license: "GPL-3.0 / CC BY-NC-SA 4.0",
        source: "https://github.com/NovaSquirrel/NovaTheSquirrel",
    },
    {
        id: "croom",
        title: "Concentration Room",
        kind: "retro",
        system: "NES",
        core: "nes",
        rom: "croom.nes",
        players: "1–2",
        description: "Memory mit Story-, Solo- und Duell-Modus.",
        author: "Damian Yerrick",
        license: "GPL-3.0",
        source: "https://github.com/pinobatch/croom-nes",
    },
    {
        id: "libbet",
        title: "Libbet and the Magic Floor",
        kind: "retro",
        system: "Game Boy",
        core: "gb",
        rom: "libbet.gb",
        players: "1",
        description: "Knobel-Spiel: jede Bodenplatte einmal berollen.",
        author: "Damian Yerrick",
        license: "zlib",
        source: "https://github.com/pinobatch/libbet",
    },
];

export const ENGINE_CREDITS = [
    { title: "EmulatorJS", author: "EmulatorJS contributors", license: "GPL-3.0", source: "https://github.com/EmulatorJS/EmulatorJS" },
];
